#!/bin/bash

set -e

docker pull ghcr.io/zhuorantan/devenv

docker run --name zt-devenv -u 0:0 -e PUID=$(id -u) -e PGID=$(id -g) --entrypoint /setup_user ghcr.io/zhuorantan/devenv
docker commit zt-devenv ghcr.io/zhuorantan/devenv
docker container rm zt-devenv

docker run --name zt-devenv -u $(id -u):$(id -g) --entrypoint zsh ghcr.io/zhuorantan/devenv -c 'nvim --headless "+Lazy! sync" +qa'
docker commit zt-devenv ghcr.io/zhuorantan/devenv
docker container rm zt-devenv
