#!/bin/bash

set -e

if ! docker image inspect "devenv-${USER}" >/dev/null 2>&1; then
  bash -c "$(curl -L zhuoran.dev/build)"
fi

if [[ $(id -u) -eq 0]]; then
  WORKSPACE="/root"
else
  WORKSPACE="/home/ubuntu/workspace/$(basename ${PWD})"
fi

docker run --rm --name "devenv-${USER}" --hostname devenv -v /etc/localtime:/etc/localtime:ro -v ${PWD}:${WORKSPACE} -w ${WORKSPACE} -it "devenv-${USER}"
